kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: elektricnePolnilnice@localhost
      connection-url: jdbc:postgresql://localhost:5432/elektricnePolnilnice
      username: postgres
      password: postgres
  security:
    keycloak:
      json: '{
              "realm": "polnilnice-relm",
              "bearer-only": true,
              "auth-server-url": "http://localhost:8082/auth/",
              "ssl-required": "external",
              "resource": "polnilnice-api",
              "confidential-port": 0
            }'
  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-check:
        connection-url: jdbc:postgresql://localhost:5432/elektricnePolnilnice
        username: postgres
        password: postgres
integration:
  zasedenost:
    base-url: http://localhost:8081/v1
  upravljanje:
    base-url: http://localhost:8083/v1