kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: elektricnePolnilnice@localhost
      connection-url: jdbc:postgresql://localhost:5432/elektricnePolnilnice
      username: postgres
      password: postgres
integration:
  zasedenost:
    base-url: http://localhost:8081/v1