kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: elektricnePolnilnice@localhost
      connection-url: jdbc:postgresql://localhost:5432/uporabniki
      username: postgres
      password: postgres