kumuluzee:
  ...
  datasources:
      - jndi-name: jdbc/LokacijskiOpomnikiDS
        connection-url: jdbc:postgresql://localhost:5432/elektricnePolnilnice
        username: postgres
        password: postgres